"""create analysis tables

Revision ID: f230532edd5e
Revises:
Create Date: 2026-09-10 23:10:44.322112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f230532edd5e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('match_id', sa.String(length=128), nullable=False),
    sa.Column('map_name', sa.String(length=64), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('rounds_played', sa.Integer(), nullable=False),
    sa.Column('score_ct', sa.Integer(), nullable=False),
    sa.Column('score_t', sa.Integer(), nullable=False),
    sa.Column('winner_side', sa.String(length=16), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('validation_error', sa.Text(), nullable=True),
    sa.Column('analysis_version', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('match_id')
    )
    op.create_table('match_players',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.String(length=128), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('steam_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('rounds_played', sa.Integer(), nullable=False),
    sa.Column('kills', sa.Integer(), nullable=False),
    sa.Column('deaths', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('headshots', sa.Integer(), nullable=False),
    sa.Column('damage', sa.Float(), nullable=False),
    sa.Column('kd', sa.Float(), nullable=False),
    sa.Column('adr', sa.Float(), nullable=False),
    sa.Column('headshot_pct', sa.Float(), nullable=False),
    sa.Column('kast_rounds', sa.Integer(), nullable=False),
    sa.Column('kast_pct', sa.Float(), nullable=False),
    sa.Column('survived_rounds', sa.Integer(), nullable=False),
    sa.Column('survival_pct', sa.Float(), nullable=False),
    sa.Column('entry_kills', sa.Integer(), nullable=False),
    sa.Column('entry_deaths', sa.Integer(), nullable=False),
    sa.Column('he_damage', sa.Float(), nullable=False),
    sa.Column('inferno_damage', sa.Float(), nullable=False),
    sa.Column('enemies_flashed', sa.Integer(), nullable=False),
    sa.Column('flash_duration', sa.Float(), nullable=False),
    sa.Column('clutches_won', sa.Integer(), nullable=False),
    sa.Column('trade_kills', sa.Integer(), nullable=False),
    sa.Column('traded_deaths', sa.Integer(), nullable=False),
    sa.Column('two_k_rounds', sa.Integer(), nullable=False),
    sa.Column('three_k_rounds', sa.Integer(), nullable=False),
    sa.Column('four_k_rounds', sa.Integer(), nullable=False),
    sa.Column('five_k_rounds', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'position', name='uq_match_players_match_position'),
    sa.UniqueConstraint('match_id', 'steam_id', name='uq_match_players_match_steam')
    )
    op.create_index(op.f('ix_match_players_match_id'), 'match_players', ['match_id'], unique=False)
    op.create_index(op.f('ix_match_players_steam_id'), 'match_players', ['steam_id'], unique=False)
    op.create_table('findings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_player_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('side', sa.String(length=16), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['match_player_id'], ['match_players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_player_id', 'position', name='uq_findings_player_position')
    )
    op.create_index(op.f('ix_findings_match_player_id'), 'findings', ['match_player_id'], unique=False)
    op.create_table('player_side_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_player_id', sa.Integer(), nullable=False),
    sa.Column('side', sa.String(length=2), nullable=False),
    sa.Column('rounds_played', sa.Integer(), nullable=False),
    sa.Column('kills', sa.Integer(), nullable=False),
    sa.Column('deaths', sa.Integer(), nullable=False),
    sa.Column('damage', sa.Float(), nullable=False),
    sa.Column('adr', sa.Float(), nullable=False),
    sa.Column('kast_rounds', sa.Integer(), nullable=False),
    sa.Column('kast_pct', sa.Float(), nullable=False),
    sa.Column('survived_rounds', sa.Integer(), nullable=False),
    sa.Column('survival_pct', sa.Float(), nullable=False),
    sa.Column('entry_kills', sa.Integer(), nullable=False),
    sa.Column('entry_deaths', sa.Integer(), nullable=False),
    sa.CheckConstraint("side IN ('CT', 'T')", name='ck_player_side_stats_side'),
    sa.ForeignKeyConstraint(['match_player_id'], ['match_players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_player_id', 'side', name='uq_player_side_stats_player_side')
    )
    op.create_index(op.f('ix_player_side_stats_match_player_id'), 'player_side_stats', ['match_player_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_side_stats_match_player_id'), table_name='player_side_stats')
    op.drop_table('player_side_stats')
    op.drop_index(op.f('ix_findings_match_player_id'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_match_players_steam_id'), table_name='match_players')
    op.drop_index(op.f('ix_match_players_match_id'), table_name='match_players')
    op.drop_table('match_players')
    op.drop_table('matches')
    # ### end Alembic commands ###
